[env:mik32v2]
platform = https://github.com/MikronMIK32/platform-mik32.git
board = start-mik32-v1
;board_build.ldscript = ram
board_build.ldscript = external/mik32v2-shared-main/ldscripts/eeprom.ld

; Правильная комбинация для вашей платы:
upload_protocol = mikron-link
debug_tool = ftdi
build_type = debug
build_flags =
    -O0
    -g3
    -I external/mik32v2-shared-main/include
    -I external/mik32v2-shared-main/periphery
    -L external/mik32v2-shared-main/ldscripts
build_src_filter =
    +<*>
    +<../external/mik32v2-shared-main/runtime/crt0.S>